Repository ec-europa/platform-dev, pull requests merged in 2018-03, with the labels that each got.

#1657 NEPT-308: Remove dependencies to dblog from profiles.
  build.test.xml
  profiles/multisite_drupal_communities/multisite_drupal_communities.info
  profiles/multisite_drupal_standard/multisite_drupal_standard.info
Labels: support

#1724 NEPT-479: Implement behat tests for newsletter feature
  resources/multisite_drupal_standard.make
  tests/features/newsletters/newsletters.feature
Labels: qtm

#1736 NEPT 317: Removing multisite_crop_and_resize and all its dependencies from platform
  profiles/common/modules/features/multisite_crop_and_resize/css/multisite_crop_and_resize.theme.css
  profiles/common/modules/features/multisite_crop_and_resize/js/multisite_crop_and_resize.image_replace.js
  profiles/common/modules/features/multisite_crop_and_resize/js/multisite_crop_and_resize.js
  profiles/common/modules/features/multisite_crop_and_resize/multisite_crop_and_resize.info
  profiles/common/modules/features/multisite_crop_and_resize/multisite_crop_and_resize.install
  profiles/common/modules/features/multisite_crop_and_resize/multisite_crop_and_resize.module
  profiles/common/modules/features/nexteuropa_feature_set/nexteuropa_feature_set.features.user_permission.inc
  profiles/common/modules/features/nexteuropa_feature_set/nexteuropa_feature_set.info
  profiles/multisite_drupal_communities/modules/custom/multisite_drupal_features_set_og/multisite_drupal_features_set_og.info
  profiles/multisite_drupal_communities/modules/features/multisite_crop_and_resize
  profiles/multisite_drupal_standard/modules/features/multisite_crop_and_resize
  resources/multisite_drupal_standard.make
Labels: Needs +1, support

#1735 NEPT 317: Remove outdated feature multisite_media_crop
  profiles/common/modules/features/multisite_crop_and_resize/multisite_crop_and_resize.info
  profiles/common/modules/features/nexteuropa_feature_set/multisite_drupal_features_set_standard/multisite_drupal_features_set_standard.info
  tests/features/menus/feature_set.feature
Labels: Needs +1, support

#1768 NEPT-469: implement behat tests for mega menus feature
  tests/features/bootstrap/FeatureContext.php
  tests/features/mega_menu/megamenu.feature
  tests/src/Context/MinkContext.php
Labels: qtm

#1742 NEPT-467: Review / document behat tests for webtools suite feature
  tests/features/webtools.feature
Labels: qtm
